name: rnaseq
channels:
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _r-mutex=1.0.0=mro_2
  - binutils_impl_linux-64=2.33.1=he6710b0_7
  - binutils_linux-64=2.33.1=h9595d00_15
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.4=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - cmake=3.19.6=h973ab73_0
  - curl=7.87.0=h5eee18b_0
  - expat=2.7.3=h3385a95_0
  - fontconfig=2.14.1=h52c9d5c_1
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_15
  - gettext=0.21.0=hf68c758_0
  - gfortran_impl_linux-64=7.3.0=hdf63c60_1
  - gfortran_linux-64=7.3.0=h553295d_15
  - glib=2.69.1=h4ff587b_1
  - graphite2=1.3.14=h295c915_1
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_15
  - harfbuzz=4.3.0=hf52aaf7_1
  - htslib=1.13=h9093b5e_0
  - icu=58.2=he6710b0_3
  - jansson=2.14=h5eee18b_1
  - krb5=1.19.2=hac12032_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcurl=7.87.0=h91b91d3_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20210714=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libnghttp2=1.52.0=ha637b67_1
  - libpng=1.6.50=h2ed474d_0
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.9.14=h74e7548_0
  - lz4-c=1.9.4=h6a678d5_1
  - make=4.2.1=h1bed415_1
  - mro-base=3.5.1=3
  - mro-base_impl=3.5.1=h9a62091_0
  - mro-basics=3.5.1=0
  - ncurses=6.2=he6710b0_1
  - openjdk=11.0.27=hb8faadd_0
  - openssl=1.1.1w=h7f8727e_0
  - pango=1.50.7=h05da053_0
  - pcre=8.45=h295c915_0
  - picard=2.20.4=0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.0=h12debd9_1
  - r=3.5.1=mro351_0
  - r-boot=1.3_20=mro351_0
  - r-checkpoint=0.4.4=mro351_0
  - r-class=7.3_14=mro351hd10c6a6_0
  - r-cluster=2.0.7_1=mro351hac1494b_0
  - r-codetools=0.2_15=mro351hf348343_0
  - r-curl=3.2=mro351hd10c6a6_1
  - r-deployrrserve=9.0.0=mro351_0
  - r-doparallel=1.0.13=mro351_0
  - r-foreach=1.5.0=mro351_0
  - r-foreign=0.8_70=mro351_0
  - r-iterators=1.0.10=mro351hf348343_0
  - r-jsonlite=1.5=mro351hd10c6a6_0
  - r-kernsmooth=2.23_15=mro351hac1494b_0
  - r-lattice=0.20_35=mro351hd10c6a6_0
  - r-mass=7.3_49=mro351_0
  - r-matrix=1.2_14=mro351hac1494b_0
  - r-mgcv=1.8_23=mro351_0
  - r-microsoftr=3.5.0.108=mro351_0
  - r-nlme=3.1_137=mro351hac1494b_0
  - r-nnet=7.3_12=mro351hd10c6a6_0
  - r-png=0.1_7=mro351hd10c6a6_0
  - r-r6=2.2.2=mro351hf348343_0
  - r-recommended=3.5.1=mro351_0
  - r-revoioq=10.0.0=mro351_0
  - r-revomods=11.0.0=mro351_0
  - r-revoutils=11.0.0=mro351_0
  - r-revoutilsmath=11.0.0=mro351_0
  - r-rpart=4.1_13=mro351hd10c6a6_0
  - r-runit=0.4.26=mro351_0
  - r-spatial=7.3_11=mro351_0
  - r-survival=2.41_3=mro351_0
  - readline=8.1=h27cfd23_0
  - rhash=1.4.1=h3c74f83_1
  - rsem=1.2.28=0
  - samtools=1.13=h8c37831_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.40.1=h5082296_0
  - star=2.7.10b=h9ee0642_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - unzip=6.0=h611a1e1_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxi=1.8.2=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxtst=1.2.5=h9b100fa_3
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=hd233ad5_2
  - zstd=1.4.9=haebb681_0
